trigger: none

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.0.x'  # Install .NET 9.0

  - script: dotnet restore
    displayName: 'Restore dependencies'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--configuration Release -o $(Build.ArtifactStagingDirectory)/publish'
    displayName: 'Publish the project'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/FlipsoEcommerceApp.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/FlipsoEcommerceApp.zip'
      artifactName: 'drop'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Pay-As-You-Go(9a668e8f-ad3f-48a1-94cb-fbcf50b35167)'
      appType: 'webApp'
      WebAppName: 'flipsoecommerceapp'
      package: '$(Build.ArtifactStagingDirectory)/drop/FlipsoEcommerceApp.zip'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Pay-As-You-Go(9a668e8f-ad3f-48a1-94cb-fbcf50b35167)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp log config --name flipsoecommerceapp --resource-group flipsoecommerceapp --detailed-error-messages true
    displayName: 'Enable Detailed Error Messages'

  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: 'Pay-As-You-Go(9a668e8f-ad3f-48a1-94cb-fbcf50b35167)'
      resourceGroupName: 'flipsoecommerceapp'
      appName: 'flipsoecommerceapp'
      appSettings: |
        {
          "WEBSITE_RUN_FROM_PACKAGE": "1"
        }
    displayName: 'Set WEBSITE_RUN_FROM_PACKAGE'
