trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.0.x'  # Install .NET 9.0

  - script: dotnet build
    displayName: 'Build the project'

  - script: dotnet test
    displayName: 'Run unit tests'

  - powershell: |
      New-Item -Path $(Build.ArtifactStagingDirectory)\app -ItemType Directory -Force
      Copy-Item -Path "$(System.DefaultWorkingDirectory)\*" -Recurse -Destination $(Build.ArtifactStagingDirectory)\app
      Compress-Archive -Path $(Build.ArtifactStagingDirectory)\app\* -DestinationPath $(Build.ArtifactStagingDirectory)\FlipsoEcommerceApp.zip
    displayName: 'Create deployment zip'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)\FlipsoEcommerceApp.zip'
      artifactName: 'drop'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Pay-As-You-Go(9a668e8f-ad3f-48a1-94cb-fbcf50b35167)'
      appType: 'webApp'
      WebAppName: 'flipsoecommerceapp'
      package: '$(Build.ArtifactStagingDirectory)/drop/FlipsoEcommerceApp.zip'
